### ISSUE TITLE
Add option to skip downloads of archives larger than xxx MiB

### ISSUE THREAD

**Issue by Jaifroid** [DocDrydenn/kiwix-zim#10]
As I prefer to download large ZIMs over BitTorrent (so I can stop and start, and to spread server load), I'd like to be able to set a size threshold over which a ZIM archive won't be downloaded (and the existing archive won't be purged).

**Comment by DocDrydenn** [comment]
This one should be pretty easy to add as well.

**Comment by jojo2357** [comment]
@Jaifroid slightly unrelated, but how do you run a p2p torrent download? I found where kiwix hides those links, so maybe I could also add support for that :eyes: 

https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim.mirrorlist

why does kiwix *always* think i am in the EU? it will always pass up downloading from `dumps.wikimedia.org` because kiwix puts the eu at higher priority, despite my being in the us.

also found some mirrorbrain docs that might be helpful: https://github.com/poeml/mirrorbrain/blob/76f2909e33004a7f5e0dd52b816881eb9fbd4246/mod_mirrorbrain/mod_mirrorbrain.c#L1440

**Comment by Jaifroid** [comment]
@jojo2357 Yes, the mirrorlist is useful, and also replacing `.mirrorlist` with `.meta4` will get an XML page with quite a lot of useful info, including hashes and mirrors.

To get a dedicated torrent link just replace `.mirrorlist` with `.torrent`. You can also get a `magnet` link by using... you guessed it... `.magnet`. However, I find that `.torrent` files are faster to start downloading than `magnet` links, as the latter need to do a lot of discovery first. Regarding downloading the file, I just use qBittorrent. I don't think it's worth implementing this inside your software, it would bloat it too much. You could just offer the torrent file and/or the magnet link for download, like I do in https://pwa.kiwix.org (in the Library under Configuration).

Not sure about the geolocation, because I'm in GB, but GB is listed above the continent in the `meta4` list, not sure if that helps:

```
    <!-- Found 10 mirrors: 0 in the same network prefix, 0 in the same autonomous system,
         1 handling this country, 7 in the same region, 2 elsewhere -->

    <!-- Mirrors in the same network (unknown): -->

    <!-- Mirrors in the same AS (unknown): -->

    <!-- Mirrors which handle this country (GB): -->
    <url location="gb" priority="1">https://www.mirrorservice.org/sites/download.kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>

    <!-- Mirrors in the same continent (EU): -->
    <url location="dk" priority="2">https://mirrors.dotsrc.org/kiwix/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="se" priority="3">https://saimei.ftp.acc.umu.se/mirror/kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="de" priority="4">https://ftp.fau.de/kiwix/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="se" priority="5">https://laotzu.ftp.acc.umu.se/mirror/kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="md" priority="6">https://md.mirrors.hacktegic.com/kiwix-md/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="nl" priority="7">https://ftp.nluug.nl/pub/kiwix/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="fr" priority="8">https://mirror.download.kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>

    <!-- Mirrors in the rest of the world: -->
    <url location="us" priority="9">https://ftpmirror.your.org/pub/kiwix/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
    <url location="us" priority="10">https://dumps.wikimedia.org/kiwix/zim/wikipedia/wikipedia_en_100_2023-06.zim</url>
```

**Comment by Jaifroid** [comment]
PS I only offer torrent/magnet for large archives, >1GB or so, I think.

**Comment by jojo2357** [comment]
@Jaifroid kiwix's geolocation started working for me...dunno why
