### ISSUE TITLE
Script doesn't verify download prior to purging

### ISSUE THREAD

**Issue by epheterson** [DocDrydenn/kiwix-zim#3]
Tried the new script with `curl` download method and for some reason the download completed but failed to save in the directory. This didn't stop the script from purging the old file, so now that item is lost!

For each file, it should verify that the new file is in the directory (and maybe even the right file size / hash, but at least existence) prior to deleting the old one.

```
5. Downloading Updates...

      ✓ Download: https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_maxi_2022-08.zim

/volume1/docker/kiwix/kiwix-zim/kiwix-zim.sh: line 202: rev: command not found
/volume1/docker/kiwix/kiwix-zim/kiwix-zim.sh: line 202: rev: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   270  100   270    0     0    501      0 --:--:-- --:--:-- --:--:--   500
Warning: Failed to create the file /volume1/docker/kiwix/: Is a directory

  0  682M    0 16375    0     0  20050      0  9:54:49 --:--:--  9:54:49 20050
curl: (23) Failure writing output to destination

6. Purging Replaced ZIM(s)...

      ✓ Purge: /volume1/docker/kiwix/wikivoyage_en_all_maxi_2021-12.zim
```

**Comment by epheterson** [comment]
Looks like the `$FileName` variable isn't being set because `rev` doesn't exist on Synology, can you try modifying this line to do the same thing without using `rev`? Also think it's important to add the file existance check prior to purging, as who knows what could go wrong (system could run out of space, process could end early, network download could timeout, etc...).

```
            FileName=$(echo ${CleanDownloadArray[$z]} | rev | cut -d "/" -f1 | rev)
```

**Comment by epheterson** [comment]
It looks like you're just trying to get the filename (i.e. text after the last slash) which you can do like this:
```
echo ${CleanDownloadArray[$z]##*/}
```

**Comment by DocDrydenn** [comment]
Now these are the type of "issues" I like... not only do they bring up a "bug", but they come with the fix too. LOL

Give me a few and I'll push the fix out to replace the use of `rev`... it was the old original way I did it before I discovered `basename`, so I must have gotten my wires crossed somewhere. Meh. Easy fix.

The purge verification will follow soon after.

**Comment by DocDrydenn** [comment]
v1.9
Replace `rev` commands.
Verification of new ZIM(s) prior to purge of old ZIM(s).
