### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by legoktm** [DocDrydenn/kiwix-zim#41]
Hi, could new releases be tagged for 3.2 and 3.3? (In Debian we use the tags to [track what the latest version](https://qa.debian.org/cgi-bin/watch?pkg=kiwix-zim-updater) is, so I had missed that new features had been added.)

**Comment by jojo2357** [comment]
I did 3.3, totally forgot about 3.2, but it wasnt a big deal. Can figure out how to add it but hopefully this works! Thanks for the work.

**Comment by legoktm** [comment]
Perfect, thank you!
