### ISSUE TITLE
SHA256 (256-bit) checksums

### ISSUE THREAD

**Issue by DocDrydenn** [DocDrydenn/kiwix-zim#6]
Researching the ability to validate SHA256 (256-bit) checksums.

- SHA256 checksums are available from the servers. Just add `.sha256` to the end of the file's link.
- `sha256sum` seems to be a default app/program on most Linux distros.

Please provide input on what the script should be expected to do.

Should these checksum files be saved along side the ZIMs and kept? Should they be purged after validation? Should the script always validate checksums?

I'm just stuck on what the "flow" should be. Please help me visualize this.

**Comment by jojo2357** [comment]
I think they should be downloaded, then the file they check for. After, check that the two match, then purge. Could always pass a flag to keep them or to skip checking them.

Imo, the most likely errors are going to come later in the script execution (especially with larger files) so getting the checksum(s?) first would be imperative in the case of an interrupted/incomplete transmission.

**Comment by jojo2357** [comment]
I cannot find checksums on the mirror `https://ftpmirror.your.org/pub/kiwix/zim/wikipedia/wikipedia_en_all_maxi_2023-04.zim.sha256` does not exist, however on the main site, `https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2023-04.zim.sha256` does exist.

**Comment by Jaifroid** [comment]
These are mirrorbrain features, which this script already uses to find the mirrors (via the meta4 info). Getting the sha256 that the server expects and then verifying after download should probably be an optional feature, as it takes some time to compute a sha256 of a very large ZIM archive -- unless it can be done on-the-fly during download.

**Comment by jojo2357** [comment]
It took 12 minutes to sha256 checksum my wikipedia archive and 4.5 to md5sum it, so I see your point. Maybe there could be two options: validate-library and checksum-new-files ? One that will find the checksums, and calculate checksums for all of the

**Comment by jojo2357** [comment]
It takes this long, but lets not forget that downloading wikipedia takes over an hour already, which makes the checksum look a lot less expensive
