### ISSUE TITLE
Invalid args does not immediately halt script

### ISSUE THREAD

**Issue by jojo2357** [DocDrydenn/kiwix-zim#8]
Running `kiwix-zim.sh` with no extra arguments does not error out immediately, despite the obvious misconfiguration. May I suggest checking the `ZIMPath` is present *before* calling `master_scrape`? I would also suggest a much more scalable args parser. Rather than hardcoding support for only 3 args.

**Comment by jojo2357** [comment]
Fixed by #9

**Comment by DocDrydenn** [comment]
Nice! Thanks for the help.
